### ISSUE TITLE
FTP plugin problem | errorcode 123

### ISSUE THREAD

**Issue by cheloooveg** [ashkulz/NppFTP#215]
### Description of the Issue

While opening files from website with notepad++ ftp plugin I have an errorcode 123
### Steps to Reproduce the Issue

1. Install ftp plugin
2. Have access to website wih Host, Login!!!, Password
3. Have errorcode 123 trying to open any file 

### Expected Behavior

File from website will open in notepad++
### Actual Behavior

Have an errorcode 123
### Debug Information

https://notepad-plus-plus.org/community/topic/15373/ftp-plugin-problem-errorcode-123

**Comment by chcg** [comment]
Seems to be a duplicate to #193 with the reserved chars of windows file system.

**Comment by stemaste62** [comment]
Hi,
yes, the problem is the special character that is _necessary_ to connect to IIS FTP.
The pipe character | divide canonical name FTP and name account for IIS to recognize a right service.
Example account: <ftp url>|<name account>  
Now, if you want to work with IIS, you cannot save a cache with this syntax, this is banaly wrong.

**Comment by shrutp** [comment]
Can you tell me what is solution to this problem?

> Hi,
> yes, the problem is the special character that is _necessary_ to connect to IIS FTP.
> The pipe character | divide canonical name FTP and name account for IIS to recognize a right service.
> Example account ftp: ftp.pippo.com|userone
> There is no other way to write it
> Now, if you want to work with IIS, you cannot save in local cache with this syntax, this is banaly wrong.

**Comment by chcg** [comment]
This is not fixed, but just closed as duplicate to #193.
