### ISSUE TITLE
Download speed via SFTP is slow

### ISSUE THREAD

**Issue by tiedaerial** [ashkulz/NppFTP#90]
Comparing to downloading a log file via WinSCP, downloading via NppFTP takes 4-5 times slower.

**Comment by Krzysiu** [comment]
Here it's the same. Could be thing with your sshd config/WinSCP. The faster isn't always better. In SSH it could mean e.g. worse encryption.

**Comment by TinoDidriksen** [comment]
With 0.29.4, NppFTP's SFTP is still absurdly slow.

For a 500 KiB text file that scp and rsync transfer in <0.1 seconds, NppFTP takes 11 seconds. Yes, two orders of magnitude slower.

Even without ssh compression, plain scp/rsync get 3.26 MB/s. With ssh or rsync compression, it's up to 5.2 MB/s. NppFTP gets 25 KB/s.

Tested fetching the same file from other computers (both Mac and Windows) and clients, and all are in the <0.1 second range. Only NppFTP takes over 10 seconds.

Maybe SSH Compression is not enabled? Maybe it's reporting progress too often so that UI updates are holding back the actual download? Something is certainly broken.

**Comment by chcg** [comment]
Please check version v0.29.5 which should improve the speed for sftp connections.
